.TH ARIA2T 1 "14 July 2020"
.SH NAME
aria2t \- an aria2c terminal frontend

.SH SYNOPSIS
.SY aria2t
.R [OPTIONS]
.
.SH DESCRIPTION
.B aria2t
is a low footprint terminal frontend for
.BR aria2c (1).
.
.SH OPTIONS
.TP
.BI \-\-select-gid\  gid
Select download with
.IR gid .
.
.TP
.BI \-\-select-file\  path
Select download matching
.IR path
and switch to file view.
.
.SH TERMINOLOGY
.SS Session file
A temporary file that used for exchanging data between aria2t and user (actions).
.
.SS Actions
Actions are executable programs, used for customizing the behavior of
.IR aria2t .
.sp
They always receive the following arguments:
.
.IP 1.
Selection GID (or empty if there are none).
.IP 2.
Path to the
.IR "session file" .
.PP
If an action terminates with failure, in-progress operation is cancelled. When
an actions does not exist, either a default, builtin action is executed or it
is treated like it was terminated with success.
.
.SH USAGE
.SS "Keyboard Control"
.TP
.BR k ,\  UP
Move selection upwards.
.
.TP
.BR j ,\  DOWN
Move selection downwards.
.
.TP
.B CTRL-U
Move selection half-screen up.
.
.TP
.B CTRL-D
Move selection half-screen down.
.
.TP
.BR g ,\  HOME
Select first.
.
.TP
.BR G ,\  END
Select last.
.
.TP
.B N
Jump to download that selection follows.
.
.TP
.B K
Move selected download forward in the queue.
.
.TP
.B J
Move selected download backward in the queue.
.
.TP
.BR s ,\  S
Start (unpause) selected/all download(s).
.
.TP
.BR p ,\  P
Pause selected/all download(s).
.
.TP
.BR a ,\  A ,\  +
Add download(s) from
.IR "session file" .
Open
.I session file
for editing unless there are associated actions. Select lastly added download.
.sp
For the expected format refer to aria2's
.IR "Input File" .
Note that URIs that end with
.BR .torrent \ and\  .meta4 \ or\  .metalink
and refer to a readable file on the local filesystem, are got uploaded to
aria2 as a blob.
.sp
Insert downloads after the selection in the queue.
.
.TP
.BR i ,\  I
Write selected download/global options in a
.BR = -separated
key-value format into the
.IR "session file" .
Open
.I session file
for viewing unless there are associated actions.
Edit the file to change options.
.
.TP
.BR D ,\  DEL
Remove download unless there is an action for \*(lqD\*(rq.
.
.TP
.BR x ,\  X
Remove download result for selection/all downloads.
.
.TP
.BR v ,\  RIGHT
Switch to next view.
.
.TP
.BR V ,\  LEFT
Switch to previous view.
.
.TP
.B !
Do next command by force. With Torrent downloads, for example, it means that it
will not contant to tracker(s).
.
.TP
.B RETURN
If standard output is not connected to a terminal, print selected GID and exit.
.
.TP
.B q
Go back to default view. On default view quit.
.
.TP
.B Z
Quit program.
.
.TP
.B Ctrl-C
Quit program with failure.
.
.TP
.B CTRL-L
Reinitialize connection.
.
.TP
.B Q
Run action \*(lqQ\*(rq then shut down aria2.
.
.TP
.R (other)
Run action named like the pressed key. Uses
.BR keyname (3x).
.
.SS Views
The following views are available (in this order):
.IP \(bu
.BR Downloads \ (default).
Shows downloads in an auto-ordered list: Topmost the queued
and currently active ones; completed downloads and errors at the bottom;
everything else is in-between.
.IP \(bu
.BR Files.
Shows download state and path for files of a download, URIs of files and servers used for downloading a
URI. Starred (\*(lq*\*(rq) URIs are the ones that were used for downloading. Dashed (\*(lq----\*(rq)
progress means an unselected file.
.IP \(bu
.BR Peers.
Shows connected BitTorrent peers\(aq IP address, port number, (their) progress
and download speed, speed information about how fast aria2 downloads and uploads
from/to them (dashes means choking).
.PP
.
.SH ENVIRONMENT
.TP
.B ARIA_RPC_HOST
Hostname of the RPC endpoint to connect to.
.sp
Default: 127.0.0.1.
.
.TP
.B ARIA_RPC_PORT
Port number of the RPC endpoint to connect to.
.sp
Default: 6800.
.
.TP
.B ARIA_RPC_SECRET
See
.I RPC authorization secret token
in
.BR aria2c (1).
.sp
Default: (empty).
.
.TP
.B ARIA2T_CONFIG
Configuration root directory.
.sp
Default:
.IR $HOME/.config/aria2t .
.
.TP
.B VISUAL, EDITOR
Used program for opening
.I session file
for editing.
.sp
Default:
.BR vi (1).
.
.TP
.B PAGER
Used program for opening
.I session file
for viewing.
.sp
Default:
.BR less (1).
.
.TP
.B TMPDIR
Where to create
.I session file.
.sp
Default:
.IR /tmp .
.
.SH FILES
.TP
.I $ARIA2T_CONFIG/actions
Actions directory.
.TP
.I $TMPDIR/aria2t.XXXXXX
Session file.
.
.SH EXAMPLE
Connect to “127.0.0.1:16800” using “$$secret$$” token.
.sp
.B env ARIA_RPC_PORT=16800 'ARIA_RPC_SECRET=$$secret$$' aria2t
.sp
.
.SH BUGS
Please report bugs at
\%https://github.com/zsugabubus/aria2t/issues.
.
.SH SEE ALSO
.BR aria2c (1)
.
.SH AUTHORS
zsugabubus
.
.SH LICENSE
GPLv3+
