.TH ARIA2T 1 "14 July 2020"
.SH NAME
aria2t \- an aria2c terminal frontend

.SH SYNOPSIS
.SY aria2t

.SH DESCRIPTION
.B aria2t
is a simple, low footprint frontend for aria2c(1).

.SH KEYBOARD CONTROL
.
.TP
.B k, UP
Move selection upwards.
.
.TP
.B j, DOWN
Move selection downwards.
.
.TP
.B CTRL-U
Move selection half-screen up.
.
.TP
.B CTRL-D
Move selection half-screen down.
.
.TP
.B g, HOME
Select first.
.
.TP
.B G, END
Select last.
.
.TP
.B s, S
Start (unpause) selected/all download(s).
.
.TP
.B p, P
Pause selected/all download(s).
.
.TP
.B K
Move selected download forward in the queue.
.
.TP
.B J
Move selected download backward in the queue.
.
.TP
.B N
Jump to download that selection follows.
.
.TP
.B a, A, +
Try running same-named action or open \fR$EDITOR\fR then add download(s) from file (one per line).
.sp
Lines ending with \fB.torrent\fR, \fB.meta4\fR/\fB.metalink\fR are treated
like Torrent and Metalink files on the local filesystem. In every other
case and if upload fails for some reason (e.g. file not readable or it is really just
an URI that ends with one of these extensions) are treated like an URI.
.sp
Downloads inserted after the selection in the queue.
.
.TP
.B D, DEL
Remove download then run action \*(lqD\*(rq.
.
.TP
.B x, X
Remove download result for selection/all downloads.
.
.TP
.B i, I
Try running same-named action or show selected download/global options in \fI$PAGER\fR. For changing an option
edit the file. (For example with \fIless(1)\fR you can invoke \fI$EDITOR\fR
by \fBv\fR.)
.
.TP
.B CTRL-L
Re-request all downloads. Tries reconnect if needed.
.
.TP
.B v, V
Switch to next/previous view.
.
.TP
.B !
Do next command by force.
.
.TP
.B Q
Shutdown \fIaria2c\fR\&.
.
.TP
.B q
Go back to default view. On default view quit.
.
.TP
.B Z
Quit program.
.
.TP
.B Return
If standard output is not connected to a terminal, print selected GID and exit.
.
.TP
.B Ctrl-C
Quit program with failure.
.
.TP
.R (everything else)
Run action named like pressed key.
.
.SH ACTIONS
.
Actions are executable files under \*(lq\fB$ARIA2T_CONFIG\fR/actions\*(rq that
you can invoke by pressing a key.
.
.SH ENVIRONMENT
.
.TP
.I ARIA_RPC_HOST
Hostname of the RPC endpoint to connect to.
.sp
Default: 127.0.0.1.
.
.TP
.I ARIA_RPC_PORT
Port number of the RPC endpoint to connect to.
.sp
Default: 6800.
.
.TP
.I ARIA_RPC_SECRET
See
.I RPC authorization secret token
in aria2c(1)\&.
.sp
Default: (empty).
.
.TP
.I ARIA2T_CONFIG
Set configuration root directory.
.sp
Default: $HOME/.config/aria2t.
.
.SH EXAMPLE
Connect to “127.0.0.1:16800” using “$$secret$$” token.
.sp
.B env ARIA_RPC_PORT=16800 'ARIA_RPC_SECRET=$$secret$$' aria2t
.sp
.
.SH BUGS
Please report bugs at
\%https://github.com/zsugabubus/aria2t/issues.
.
.SH SEE ALSO
.BR aria2c(1)
.
.SH AUTHORS
zsugabubus
.
.SH LICENSE
GPLv3+
