.TH ARIA2T 1 "25 Januar 2020"
.SH NAME
aria2t \- an aria2c frontend

.SH SYNOPSIS
.SY aria2t

.SH DESCRIPTION
.B aria2t
is a simple, minimal, low footprint frontend for aria2c(1).

.SH KEYBOARD CONTROL
.
.TP
.B k, UP
Select line above.
.
.TP
.B j, DOWN
Select line below.
.
.TP
.B g
Select first line.
.
.TP
.B G
Select last line.
.
.TP
.B p, SPACE
Toggle paused state of the selected download.
.
.TP
.B P
On an unpaused download pause all, on a paused download unpause all.
.
.TP
.B F9
Shutdown
.IR aria2c
server\&.
.
.TP
.B q
Quit program.
.
.TP
.B Ctrl-c
Quit program with failure.

.SH ENVIRONMENT
.
.TP
.I ARIA_RPC_HOST
Hostname of the RPC endpoint to connect to.
.sp
Default:
.IR 127.0.0.1 \&.
.
.TP
.I ARIA_RPC_PORT
Port number of the RPC endpoint to connect to.
.sp
Default:
.IR 6800 \&.
.
.TP
.I ARIA_RPC_SECRET
See
.I RPC authorization secret token
in aria2c(1)\&.
.sp
Default: (empty).

.SH EXAMPLE
Connect to “127.0.0.1:16800” using “$$secret$$” token.
.sp
.B env ARIA_RPC_PORT=16800 'ARIA_RPC_SECRET=$$secret$$' aria2t
.sp

.SH BUGS
Please report bugs at
\%https://github.com/zsugabubus/aria2t/issues.

.SH SEE ALSO
.BR aria2c(1)

.SH AUTHORS
zsugabubus (but who cares?!)

.SH LICENSE
GPLv3+
